spring.application.name=warehouse-management-system
server.port=8080

# ===============================
# DATABASE CONNECTION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/warehouse_management_system
spring.datasource.username=postgres
spring.datasource.password=postgre9094

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# SHOW SQL (optional)
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
